const sampleBlogs = [
  {
    blogDesktopImg: "",
    blogMobileImg: "",
    author: "",
    date: "",
    title: "",
    category: "",
    body: "",
  },
  {
    blogDesktopImg: "",
    blogMobileImg: "",
    author: "",
    date: "",
    title: "",
    category: "",
    body: "",
  },
  {
    blogDesktopImg: "",
    blogMobileImg: "",
    author: "",
    date: "",
    title: "",
    category: "",
    body: "",
  },
  {
    blogDesktopImg: "",
    blogMobileImg: "",
    author: "",
    date: "",
    title: "",
    category: "",
    body: "",
  },
  {
    blogDesktopImg: "",
    blogMobileImg: "",
    author: "",
    date: "",
    title: "",
    category: "",
    body: "",
  },
];
