export const NEW_BLOG_UPLOAD = NEW_BLOG_UPLOAD;
export const NEW_BLOG_UPLOAD_FAILED = NEW_BLOG_UPLOAD_FAILED;

export const DELETE_BLOG = DELETE_BLOG;
export const DELETE_BLOG_FAILED = DELETE_BLOG_FAILED;

export const EDIT_BLOG = EDIT_BLOG;
export const EDIT_BLOG_FAILED = EDIT_BLOG_FAILED;

export const GET_ALL_BLOGS = GET_ALL_BLOGS;
export const GET_ALL_BLOGS_FAILED = GET_ALL_BLOGS_FAILED;

export const GET_INDIVIDUAL_BLOG = GET_INDIVIDUAL_BLOG;
export const GET_INDIVIDUAL_BLOG_FAILED = GET_INDIVIDUAL_BLOG_FAILED;
